version: '3'
services:
  web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:dev_password@db:5432/passt
      TEST_DATABASE_URL: postgres://postgres:dev_password@db:5432/passtTest
  db:
      image: postgres
      environment:
        POSTGRES_PASSWORD: dev_password
      ports:
        - 5432:5432