version: '3'
services:
  web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      PORT: 3000
      MONGODB_URI: 'mongodb://mongodb:27017/passt'
      TEST_MONGODB_URI: 'mongodb://mongodb:27017/passtTest'
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"