name: Test
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create migrations
        run: docker-compose run web npm run typeorm migration:run 
      - name: Run tests
        run: docker-compose run web npm test